### ISSUE TITLE
declare requirements more formally

### ISSUE THREAD

**Issue by balhoff** [sap218/jabberwocky#9]
I am not that sophisticated of a python developer, but I often see a [`requirements.txt`](https://pip.pypa.io/en/latest/user_guide/#requirements-files) used to declare requirements.

I did successfully install the software by using the prerequisites command in the README, but breaking these out into a dependencies file would probably be a good idea.

**Comment by balhoff** [comment]
(this is part of JOSS review https://github.com/openjournals/joss-reviews/issues/2168)

**Comment by sap218** [comment]
requirements.txt included with instructions :-)
